name: Playwright Tests -> Xray
on:
  push:
    branches: [main]
  pull_request:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      #Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

      #Setup Node
    - name: Setup Node
      uses: actions/setup-node@v4 
      with:
        node-version: 18

      #Install dependencies
    - name: Install dependencies
      run: npm ci

      #Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

      #Run Playwright tests with JUnit reporter
    - name: Run Playwright tests
      run: npx playwright test --reporter=junit --output=test-results

      #Verify JUnit resukts exist
    - name: Check JUnit results
      run: |
        ls -la test-results
        cat test-results/*.xml

    - name: Authenticate with Xray Cloud
      id: xray-auth
      run: |
          echo "Authenticating to Xray Cloud..."
          TOKEN=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "{\"client_id\": \"${{secrets.XRAY_CLIENT_ID}}\", \"client_secret\": \"${{secrets.XRAY_CLIENT_SECRET}}\"}" \
            https://xray.cloud.getxray.app/api/v2/authenticate | tr -d '"')
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

    - name: Upload Junit results to Xray Cloud
      if: always()
      run: |
        for file in test-results/*.xml; do
        echo "Uploading $file ..."
        curl -H "Authorization: Bearer ${{ steps.xray-auth.outputs.token }}" \
             -F "file=@$file" \
             "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=TA"